### ISSUE TITLE
Add UCI view selection

### ISSUE THREAD

**Issue by rflperry** [neurodata/mvlearn#143]
## Desired Behavior
load_UCImultifeatures should be able to return a subset of the multiview data

`Xs, y = load_UCImultifeatures(views=[0,1])` should return an `Xs` of the first two views, i.e. `len(Xs) = 2`.

**Comment by gmischl1** [comment]
The select_labeled parameter is not meant for returning certain views. Rather, it is meant to select the samples with those labels. The labels for all the samples are 0-9, so select labeled will return 6 views, but each view will only have 400 samples (200 0's and 200 1's).

If the documentation is confusing, it should definitely be changed. If you think there should be the ability to select which views you want, then I can easily add that. I originally didn't because that's a pretty simple one-line call after you load the full Xs.

**Comment by rflperry** [comment]
Okay I think I just thought I knew what it did and wasn't bothering to read the docs. I'll make this issue a feature.
