### ISSUE TITLE
Gaussian Mixture Test Shuffle failing

### ISSUE THREAD

**Issue by rflperry** [neurodata/mvlearn#152]
## Expected Behavior
test_shuffle in test_gaussian_mixture should work every time per correct seeding/implementation.

## Actual Behavior
![image](https://user-images.githubusercontent.com/13107341/80620492-12f13c80-8a14-11ea-853b-cc7475705982.png)

**Comment by gmischl1** [comment]
After looking at the code, I think this might just be bad luck. The data is the same, because the random_state is set to be the same for both datasets. However, even though shuffle is True, there are only 10 samples in each dataset, so sometimes it gets unlucky. If I change it to 2 samples, it fails about 50% of the time, as I would expect. I think I'll just increase the number of samples so it hopefully never fails.
